export var listaordenes = [
  {
    Fechaingreso: '2025-02-01',
    SampleID: '2502013058',
    Origen: 'HOSPITALIZACION',
    Age: '1',
    Paciente: 'QUIROZ ANDRADE RN , .',
    Sexo: 'F',
    Historia: '1088421',
    cedula: '1354214072',
    Tipomuestra: 'KOH,EXAMEN DE GRAM,HEMOCULTIVO N° 2,EXAMEN FRESCO',
    Microorganismo: '',
    Tecnica: '',
    Valor: '',
    Antibiotico: '',
    Sensible: '',
    Fechavalidacion: '2025-02-10,2025-02-10,2025-02-10,2025-02-05',
    validador: 'FMACIAS,FMACIAS,FMACIAS,KLOOR',
    Comentario:
      'NEGATIVO\n,NO SE OBSERVAN BACTERIAS\n,SIN DESARROLLO MICROBIANO DURANTE 7 DIAS.\n(REPORTE DEFINITIVO)\n \n \n,(1) ------------------------------------------------------------------\nREPORTE PRELIMINAR: FECHA 05/02/2025 HORA 13H02\nSIN DESARROLLO MICROBIANO DURANTE 72 HORAS\n(OBSERVACION: HEMOCULTIVO EN PROCESO X 7 DIAS)\n',
    Orden: '11204931',
  },
  {
    Fechaingreso: '2025-02-01',
    SampleID: '2502013060',
    Origen: 'HOSPITALIZACION',
    Age: '1',
    Paciente: 'QUIROZ ANDRADE RN , .',
    Sexo: 'F',
    Historia: '1088421',
    cedula: '1354214072',
    Tipomuestra: 'KOH,EXAMEN DE GRAM,CULTIVO DE ORINA,EXAMEN FRESCO',
    Microorganismo: '',
    Tecnica: '',
    Valor: '',
    Antibiotico: '',
    Sensible: '',
    Fechavalidacion: '2025-02-05,2025-02-05,2025-02-05,2025-02-05',
    validador: 'KLOOR,KLOOR,KLOOR,KLOOR',
    Comentario:
      'NEGATIVO\n,BACILOS GRAM NEGATIVOS\n,,MUESTRA: ORINA\nCELULAS EPITELIALES:ESCASAS\nLEUCOCITOS: ABUNDANTES\nHONGOS:NO SE OBSERVAN\nBACTERIAS:+++\nF.MOCO:++',
    Orden: '11204825',
  },
  {
    Fechaingreso: '2025-02-02',
    SampleID: '2502023063',
    Origen: 'HOSPITALIZACION',
    Servicio: 'TERAPIA INTENSIVA NEO',
    Age: '0',
    Paciente: 'ANCHUNDIA ANCHUNDIA RN , .',
    Sexo: 'F',
    Historia: '1124488',
    cedula: '1354556555',
    Tipomuestra: 'KOH,EXAMEN DE GRAM,HEMOCULTIVO,EXAMEN FRESCO',
    Microorganismo: '',
    Tecnica: '',
    Valor: '',
    Antibiotico: '',
    Sensible: '',
    Fechavalidacion: '2025-02-10,2025-02-10,2025-02-10,2025-02-07',
    validador: 'FMACIAS,FMACIAS,FMACIAS,KLOOR',
    Comentario:
      'NEGATIVO\n,NO SE OBSERVAN BACTERIAS\n,SIN DESARROLLO MICROBIANO DURANTE 48 HORAS\n,(1) ------------------------------------------------------------------\nREPORTE PRELIMINAR: FECHA 07/02/2025 HORA 11H23\nSIN DESARROLLO MICROBIANO DURANTE 5 DIAS\n(OBSERVACION: HEMOCULTIVO EN PROCESO X 7 DIAS)\n',
    Orden: '11206421',
  },

  {
    Fechaingreso: '2025-02-01',
    SampleID: '2502013063',
    Origen: 'HOSPITALIZACION',
    Servicio: 'HOSPI HOMBRES',
    Age: '17',
    Paciente: 'PONCE MONTIEL ANNE MARIOLA , .',
    Sexo: 'F',
    Historia: '917472',
    cedula: '1351645708',
    Tipomuestra: 'KOH,EXAMEN DE GRAM,CULTIVO DE ORINA,EXAMEN FRESCO',
    Microorganismo: '',
    Tecnica: '',
    Valor: '',
    Antibiotico: '',
    Sensible: '',
    Fechavalidacion: '2025-02-05,2025-02-05,2025-02-05,2025-02-05',
    validador: 'KLOOR,KLOOR,KLOOR,KLOOR',
    Comentario:
      'NEGATIVO\n,NO SE OBSERVAN BACTERIAS\n,SIN DESARROLLO MICROBIANO DURANTE 48 HORAS\n,MUESTRA: ORINA\nCELULAS EPITELIALES:ESCASAS\nLEUCOCITOS:0-2 XC\nHEMATIES:0-1 XC\nHONGOS:NO SE OBSERVAN\nBACTERIAS:ESCASAS\nF.MOCO:+++\n',
    Orden: '11203747',
  },
  {
    Fechaingreso: '2025-02-01',
    SampleID: '2502013071',
    Origen: 'HOSPITALIZACION',
    Servicio: 'HOSPI HOMBRES',
    Age: '83',
    Paciente: 'FLORES ANCHUNDIA JOSE RAMON , .',
    Sexo: 'M',
    Historia: '627628',
    cedula: '1300581673',
    Tipomuestra: 'KOH,EXAMEN DE GRAM,CULTIVO DE ORINA,EXAMEN FRESCO',
    Microorganismo: '',
    Tecnica: '',
    Valor: '',
    Antibiotico: '',
    Sensible: '',
    Fechavalidacion: '2025-02-05,2025-02-05,2025-02-05,2025-02-05',
    validador: 'KLOOR,KLOOR,KLOOR,KLOOR',
    Comentario:
      'NEGATIVO\n,NO SE OBSERVAN BACTERIAS\n,SIN DESARROLLO MICROBIANO DURANTE 48 HORAS\n,MUESTRA: ORINA\nCELULAS EPITELIALES:ESCASAS\nLEUCOCITOS: ABUNDANTES\nHEMATIES:ABUNDANTES\nHONGOS:NO SE OBSERVAN\nBACTERIAS:ESCASAS\n',
    Orden: '11205220',
  },
  {
    Fechaingreso: '2025-02-01',
    SampleID: '2502013074',
    Origen: 'HOSPITALIZACION',
    Servicio: 'EMERGENCIAS (URG)',
    Age: '26',
    Paciente: 'TRIVIÑO MOREIRA MIRIAN ELIZABETH , .',
    Sexo: 'F',
    Historia: '1125036',
    cedula: '1351472327',
    Tipomuestra: 'KOH,EXAMEN DE GRAM,CULTIVO DE ORINA,EXAMEN FRESCO',
    Microorganismo: '',
    Tecnica: '',
    Valor: '',
    Antibiotico: '',
    Sensible: '',
    Fechavalidacion: '2025-02-05,2025-02-05,2025-02-05,2025-02-05',
    validador: 'KLOOR,KLOOR,KLOOR,KLOOR',
    Comentario:
      'NEGATIVO\n,NO SE OBSERVAN BACTERIAS\n,SIN DESARROLLO MICROBIANO DURANTE 48 HORAS\n,MUESTRA: ORINA\nCELULAS EPITELIALES:+++\nLEUCOCITOS:5-7 XC\nHEMATIES:ABUNDANTES\nHONGOS:NO SE OBSERVAN\nBACTERIAS:ESCASAS\nF.MOCO:++\n\n',
    Orden: '11205235',
  },
  {
    Fechaingreso: '2025-02-01',
    SampleID: '2502013092',
    Origen: 'HOSPITALIZACION',
    Servicio: 'HOSPI HOMBRES',
    Age: '75',
    Paciente: 'MENDOZA PANTA PAULA ANGELA , .',
    Sexo: 'F',
    Historia: '1005126',
    cedula: '1303279226',
    Tipomuestra: 'KOH,EXAMEN DE GRAM,HEMOCULTIVO N° 2,EXAMEN FRESCO',
    Microorganismo: '',
    Tecnica: '',
    Valor: '',
    Antibiotico: '',
    Sensible: '',
    Fechavalidacion: '2025-02-04,2025-02-03,2025-02-06,2025-02-06',
    validador: 'FMACIAS,KLOOR,KLOOR,KLOOR',
    Comentario:
      'NEGATIVO\n,BACILOS GRAM NEGATIVOS\nPENDIENTE IDENTIFICACION Y ANTIBIOGRAMA\n \n(REPORTE PRELIMINAR)\n,Klebsiella pneumoniae,fenotipicamente productora de carbapenemasa. [Tipo: Serincarbapenemasa(KPC) + Metalobetalactamasa (NDM)]\n--\nObservación:\nFavor Mantener la Vigilancia al microorganismo,Klebsiella pneumoniae,fenotipicamente productora de carbapenemasa. [Tipo: Serincarbapenemasa(KPC) + Metalobetalactamasa (NDM)]\n--\nObservación:\nFavor Mantener la Vigilancia al microorganismo',
    Orden: '11205208',
  },
  {
    Fechaingreso: '2025-02-01',
    SampleID: '2502013095',
    Origen: 'HOSPITALIZACION',
    Servicio: 'EMERGENCIAS (URG)',
    Age: '35',
    Paciente: 'MACIAS BRAVO CARMEN ANGELICA , .',
    Sexo: 'F',
    Historia: '1108883',
    cedula: '1313838474',
    Tipomuestra: 'KOH,EXAMEN DE GRAM,CULTIVO DE ORINA,EXAMEN FRESCO',
    Microorganismo: '',
    Tecnica: '',
    Valor: '',
    Antibiotico: '',
    Sensible: '',
    Fechavalidacion: '2025-02-05,2025-02-05,2025-02-05,2025-02-05',
    validador: 'KLOOR,KLOOR,KLOOR,KLOOR',
    Comentario:
      'NEGATIVO\n,NO SE OBSERVAN BACTERIAS\n,SIN DESARROLLO MICROBIANO DURANTE 48 HORAS\n,MUESTRA: ORINA\nCELULAS EPITELIALES:ESCASAS\nLEUCOCITOS:ABUNDANTES\nHEMATIES:3-5 XC\nHONGOS:NO SE OBSERVAN\nBACTERIAS:ESCASAS\n',
    Orden: '11205671',
  },
  {
    Fechaingreso: '2025-02-01',
    SampleID: '2502013096',
    Origen: 'HOSPITALIZACION',
    Servicio: 'HEMODIALISIS (HO) DIA',
    Age: '49',
    Paciente: 'ZAMBRANO ARANA HILDA CASILDA , .',
    Sexo: 'F',
    Historia: '1054824',
    cedula: '1308251139',
    Tipomuestra: 'CULTIVO DE ORINA',
    Microorganismo: 'Klebsiella pneumoniae',
    Tecnica: 'CMI',
    Valor:
      '>=32,4,<=0.12,<=0.25,<=0.12,<=0.12,<=0.25,<=1,>=16,0.5,2,64,<=16,>=320,<=4,<=4',
    Antibiotico:
      'Ampicilina-sulbactam,Cefalotina,Ceftazidima,Ceftriaxona,Cefepime,Ertapenem,Meropenem,Amicacina,Gentamicina,Ciprofloxacino,Norfloxacino,Fosfomicina,Nitrofurantoina,Trimetoprim-sulfametoxazol,Cefazolina,Cefuroxima',
    Sensible:
      'Resistente,Sensible,Sensible,Sensible,Sensible,Sensible,Sensible,Sensible,Resistente,Intermedio,Sensible,Sensible,Sensible,Resistente,Sensible,Sensible',
    Fechavalidacion: '2025-02-07',
    validador: 'KLOOR',
    Comentario: '',
    Orden: '11205507',
  },
  {
    Fechaingreso: '2025-02-01',
    SampleID: '2502013097',
    Origen: 'HOSPITALIZACION',
    Servicio: 'OBSERVACION(HO)',
    Age: '77',
    Paciente: 'MOREIRA CHAVARRIA COLOMBIA MERCEDES , .',
    Sexo: 'F',
    Historia: '819645',
    cedula: '1302747793',
    Tipomuestra: 'KOH,EXAMEN DE GRAM,CULTIVO DE ORINA,TINTA CHINA',
    Microorganismo: '',
    Tecnica: '',
    Valor: '',
    Antibiotico: '',
    Sensible: '',
    Fechavalidacion: '2025-02-05,2025-02-05,2025-02-05,2025-02-05',
    validador: 'FMACIAS,FMACIAS,FMACIAS,FMACIAS',
    Comentario:
      'NEGATIVO\n,NO SE OBSERVAN BACTERIAS\n,SIN DESARROLLO MICROBIANO DURANTE 48 HORAS\n,N/I\n',
    Orden: '11205718',
  },
  {
    Fechaingreso: '2025-02-01',
    SampleID: '2502015068',
    Origen: 'URGENCIAS',
    Servicio: 'URG.PEDIATRIA(EM)',
    Age: '7',
    Paciente: 'BAQUE MARQUEZ SOFIA MALENA , .',
    Sexo: 'F',
    Historia: '919871',
    cedula: '1352710154',
    Tipomuestra: 'KOH,EXAMEN DE GRAM,CULTIVO DE ORINA,EXAMEN FRESCO',
    Microorganismo: '',
    Tecnica: '',
    Valor: '',
    Antibiotico: '',
    Sensible: '',
    Fechavalidacion: '2025-02-05,2025-02-05,2025-02-05,2025-02-05',
    validador: 'FMACIAS,FMACIAS,FMACIAS,FMACIAS',
    Comentario:
      'NEGATIVO\n,BACILOS GRAM NEGATIVOS\n,,MUESTRA: ORINA\nCELULAS EPITELIALES:ESCASAS\nLEUCOCITOS:28-30 XC\nHEMATIES:16-18 XC\nHONGOS:NO SE OBSERVAN\nBACTERIAS:+++\nF.MOCO:ESCASO\nC.URATOS AMORFOS:+++\nC.OXALATO DE Ca:++\n',
    Orden: '11205568',
  },
  {
    Fechaingreso: '2025-02-01',
    SampleID: '2502015074',
    Origen: 'URGENCIAS',
    Servicio: 'URG.PEDIATRIA(EM)',
    Age: '9',
    Paciente: 'MANTUANO MENDOZA MILENKA KAORY , .',
    Sexo: 'F',
    Historia: '833711',
    cedula: '1352187882',
    Tipomuestra: 'KOH,EXAMEN DE GRAM,CULTIVO DE ORINA,EXAMEN FRESCO',
    Microorganismo: '',
    Tecnica: '',
    Valor: '',
    Antibiotico: '',
    Sensible: '',
    Fechavalidacion: '2025-02-05,2025-02-05,2025-02-05,2025-02-05',
    validador: 'FMACIAS,FMACIAS,FMACIAS,FMACIAS',
    Comentario:
      'NEGATIVO\n,BACILOS GRAM NEGATIVOS\n,,MUESTRA: ORINA\nCELULAS EPITELIALES:++\nLEUCOCITOS: ABUNDANTES\nHEMATIES:2-4 XC\nHONGOS:NO SE OBSERVAN\nBACTERIAS:+++\nF.MOCO:+',
    Orden: '11205609',
  },
  {
    Fechaingreso: '2025-02-02',
    SampleID: '2502023020',
    Origen: 'HOSPITALIZACION',
    Servicio: 'URG. PEDIATRICA (EM)',
    Age: '2',
    Paciente: 'FERNANDEZ MERO OSCAR ELIAN , .',
    Sexo: 'M',
    Historia: '1124704',
    cedula: '1354055376',
    Tipomuestra: 'KOH,EXAMEN DE GRAM,HEMOCULTIVO N° 2,EXAMEN FRESCO',
    Microorganismo: '',
    Tecnica: '',
    Valor: '',
    Antibiotico: '',
    Sensible: '',
    Fechavalidacion: '2025-02-10,2025-02-10,2025-02-10,2025-02-07',
    validador: 'FMACIAS,FMACIAS,FMACIAS,KLOOR',
    Comentario:
      'NEGATIVO\n,NO SE OBSERVAN BACTERIAS\n,SIN DESARROLLO MICROBIANO DURANTE 48 HORAS\n,(1) ------------------------------------------------------------------\nREPORTE PRELIMINAR: FECHA 05/02/2025 HORA 14H10\nSIN DESARROLLO MICROBIANO DURANTE 72 HORAS\n(OBSERVACION: HEMOCULTIVO EN PROCESO X 7 DIAS)\n(2) ------------------------------------------------------------------\nREPORTE PRELIMINAR: FECHA 07/02/2025 HORA 11H24\nSIN DESARROLLO MICROBIANO DURANTE 5 DIAS\n(OBSERVACION: HEMOCULTIVO EN PROCESO X 7 DIAS)\n',
    Orden: '11205897',
  },
  {
    Fechaingreso: '2025-02-02',
    SampleID: '2502023022',
    Origen: 'HOSPITALIZACION',
    Servicio: 'OBSERVACION(HO)',
    Age: '56',
    Paciente: 'VELIZ RAMON ANTONIO ELIAS , .',
    Sexo: 'M',
    Historia: '1123726',
    cedula: '1306726918',
    Tipomuestra: 'HEMOCULTIVO N° 2',
    Microorganismo: '',
    Tecnica: '',
    Valor: '',
    Antibiotico: '',
    Sensible: '',
    Fechavalidacion: '2025-02-10',
    validador: 'FMACIAS',
    Comentario: 'SIN DESARROLLO MICROBIANO DURANTE 48 HORAS\n',
    Orden: '11204889',
  },
  {
    Fechaingreso: '2025-02-02',
    SampleID: '2502023026',
    Origen: 'HOSPITALIZACION',
    Servicio: 'PED.GENERAL(HO)',
    Age: '6',
    Paciente: 'QUINDE CALDERON EMMA MICHEL , .',
    Sexo: 'F',
    Historia: '985782',
    cedula: '1352996076',
    Tipomuestra:
      'KOH,EXAMEN DE GRAM,EXAMEN FRESCO,CULTIVO DE LIQUIDO CEFALORAQUIDEO',
    Microorganismo: '',
    Tecnica: '',
    Valor: '',
    Antibiotico: '',
    Sensible: '',
    Fechavalidacion: '2025-02-05,2025-02-05,2025-02-05,2025-02-07',
    validador: 'FMACIAS,FMACIAS,FMACIAS,KLOOR',
    Comentario:
      'NEGATIVO\n,NO SE OBSERVAN BACTERIAS\n(CULTIVO EN PROCESO)\n(REPORTE PRELIMINAR)\n,LIQUIDO CEFALORRAQUIDEO\n--\nCOLOR:CRISTAL ROCA\nASPECTO:LIMPIDO\nSIN REACCION INFLAMATORIA\nHEMATIES:ESCASA CANTIDAD\n\n\n \n,SIN DESARROLLO MICROBIANO DURANTE 5 DIAS\n(REPORTE DEFINITIVO)\n',
    Orden: '11205985',
  },
  {
    Fechaingreso: '2025-02-02',
    SampleID: '2502023030',
    Origen: 'HOSPITALIZACION',
    Servicio: 'OBSERVACION(HO)',
    Age: '75',
    Paciente: 'DELGADO MERO CARMEN ISABEL , .',
    Sexo: 'F',
    Historia: '1746',
    cedula: '1300631429',
    Tipomuestra: 'KOH,EXAMEN DE GRAM,HEMOCULTIVO N° 2,EXAMEN FRESCO',
    Microorganismo: '',
    Tecnica: '',
    Valor: '',
    Antibiotico: '',
    Sensible: '',
    Fechavalidacion: '2025-02-10,2025-02-10,2025-02-10,2025-02-07',
    validador: 'FMACIAS,FMACIAS,FMACIAS,KLOOR',
    Comentario:
      'NEGATIVO\n,NO SE OBSERVAN BACTERIAS\n,SIN DESARROLLO MICROBIANO DURANTE 48 HORAS\n,(1) ------------------------------------------------------------------\nREPORTE PRELIMINAR: FECHA 05/02/2025 HORA 14H21\nSIN DESARROLLO MICROBIANO DURANTE 72 HORAS\n(OBSERVACION: HEMOCULTIVO EN PROCESO X 7 DIAS)\n(2) ------------------------------------------------------------------\nREPORTE PRELIMINAR: FECHA 07/02/2025 HORA 11H21\nSIN DESARROLLO MICROBIANO DURANTE 5 DIAS\n(OBSERVACION: HEMOCULTIVO EN PROCESO X 7 DIAS)\n\n',
    Orden: '11204904',
  },
];
